name: Publish

on:
  push:
    tags:
      - '*'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Configure JDK
          uses: actions/setup-java@v1
      - name: Test
        run: ./gradlew testDebugUnitTest

  publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure JDK
        uses: actions/setup-java@v1

      - name: Upload Artifacts
          run: ./gradlew core:install; ./gradlew core:bintrayUpload;./gradlew okmocker-reader:install; ./gradlew okmocker-reader:bintrayUpload; ./gradlew okmocker-writer:install; ./gradlew okmocker-reader:bintrayUpload
          env:
            bintray.user: ${{ secrets.BINTRAY_USER }}
            bintray.apikey: ${{ secrets.BINTRAY_API_KEY }}


